version: 2
updates:
  - package-ecosystem: "terraform"
    directories:
      - "/src"
      - "/src/modules/*"
      - "/stackit-verified-modules/*"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      terraform-providers:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
